"""Changed user table

Revision ID: b10ba6d8e74d
Revises: 70d22e568985
Create Date: 2024-04-19 10:46:05.564920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b10ba6d8e74d'
down_revision = '70d22e568985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('admin', 'employee', name='user_role_enum'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
